[graph]
all-features = true

[advisories]
vulnerability = "deny"
yanked = "warn"
unmaintained = "warn"
ignore = []

[bans]
multiple-versions = "warn"
unknown-registry = "deny"
unknown-git = "deny"
denied = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
