apiVersion: v1
kind: Service
metadata:
  name: {{ include "decentralized-app.fullname" . }}-indexer
  labels:
    {{- include "decentralized-app.labels" . | nindent 4 }}
    component: indexer
spec:
  type: {{ .Values.indexerService.service.type }}
  ports:
    - port: {{ .Values.indexerService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "decentralized-app.selectorLabels" . | nindent 4 }}
    component: indexer