apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-os
  labels:
    app: dex-os
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dex-os
  template:
    metadata:
      labels:
        app: dex-os
    spec:
      containers:
      - name: dex-os
        image: dex-os:latest
        ports:
        - containerPort: 3000
        env:
        - name: RUST_LOG
          value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: dex-os-service
spec:
  selector:
    app: dex-os
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer